name: Unit Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: checkout reposit
      - name: Setup Node
        uses: actions/setup-node@v3
      - uses: actions/cache@v3 # 👀
        id: npm-cache # 👀
        with: # 👀
         path: ~/.npm # 👀
         key: npm-${{ hashFiles('**/package-lock.json') }} 
      - run: npm ci
      - run: npm test

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - uses: actions/cache@v3 # 👀
        id: npm-cache # 👀
        with: # 👀
         path: ~/.npm # 👀
         key: npm-${{ hashFiles('**/package-lock.json') }} 
      - run: npm ci
      - run: npm run build   